"""migrate authentication to relational tables

Revision ID: 622436c321e7
Revises: 88d829523673
Create Date: 2026-07-21 20:30:15.771332
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '622436c321e7'
down_revision: Union[str, None] = '88d829523673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index('ix_sessions_expires_at', 'sessions', ['expires_at'], unique=False)
    op.create_index('ix_sessions_user_id', 'sessions', ['user_id'], unique=False)
    op.add_column('users', sa.Column('role_names', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False))
    op.add_column('users', sa.Column('permissions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False))
    op.add_column('users', sa.Column('avatar_url', sa.Text(), nullable=True))
    op.execute(sa.text("""
        INSERT INTO tenants (id, name, slug, status, settings)
        VALUES (
            '00000000-0000-0000-0000-000000000001',
            'DDOCR', 'default', 'active', '{}'::jsonb
        )
        ON CONFLICT (slug) DO NOTHING
    """))
    op.execute(sa.text("""
        INSERT INTO users (
            id, tenant_id, name, email, phone, employee_no, department,
            password_salt, password_hash, role_names, permissions, avatar_url,
            status, last_login_at, deleted_at, created_at, updated_at
        )
        SELECT
            o.id,
            (SELECT id FROM tenants WHERE slug = 'default' LIMIT 1),
            COALESCE(NULLIF(o.data->>'name', ''), 'Unknown'),
            NULLIF(lower(o.data->>'email'), ''),
            NULLIF(o.data->>'phone', ''),
            NULLIF(o.data->>'employee_no', ''),
            COALESCE(o.data->>'department', ''),
            o.data->>'password_salt',
            o.data->>'password_hash',
            COALESCE(o.data->'role_names', '["质量检测工程师"]'::json)::jsonb,
            COALESCE(o.data->'permissions', '["ocr:read","ocr:create","profile:update"]'::json)::jsonb,
            NULLIF(o.data->>'avatar_url', ''),
            CASE WHEN COALESCE((o.data->>'deleted')::boolean, false)
                 THEN 'disabled' ELSE 'active' END,
            NULLIF(o.data->>'last_login_at', '')::timestamptz,
            CASE WHEN COALESCE((o.data->>'deleted')::boolean, false)
                 THEN now() ELSE NULL END,
            COALESCE(NULLIF(o.data->>'created_at', '')::timestamptz, now()),
            COALESCE(NULLIF(o.data->>'updated_at', '')::timestamptz,
                     NULLIF(o.data->>'created_at', '')::timestamptz, now())
        FROM objects AS o
        WHERE o.kind = 'user'
        ON CONFLICT (id) DO UPDATE SET
            name = EXCLUDED.name,
            email = EXCLUDED.email,
            phone = EXCLUDED.phone,
            employee_no = EXCLUDED.employee_no,
            department = EXCLUDED.department,
            password_salt = EXCLUDED.password_salt,
            password_hash = EXCLUDED.password_hash,
            role_names = EXCLUDED.role_names,
            permissions = EXCLUDED.permissions,
            avatar_url = EXCLUDED.avatar_url,
            status = EXCLUDED.status,
            last_login_at = EXCLUDED.last_login_at,
            deleted_at = EXCLUDED.deleted_at,
            updated_at = EXCLUDED.updated_at
    """))
    op.execute(sa.text("""
        INSERT INTO sessions (token, user_id, created_at, revoked_at)
        SELECT
            COALESCE(NULLIF(o.data->>'token', ''), o.id),
            o.data->>'user_id',
            COALESCE(NULLIF(o.data->>'created_at', '')::timestamptz, now()),
            CASE WHEN COALESCE((o.data->>'revoked')::boolean, false)
                 THEN now() ELSE NULL END
        FROM objects AS o
        JOIN users AS u ON u.id = o.data->>'user_id'
        WHERE o.kind = 'session'
        ON CONFLICT (token) DO UPDATE SET
            user_id = EXCLUDED.user_id,
            revoked_at = EXCLUDED.revoked_at
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'permissions')
    op.drop_column('users', 'role_names')
    op.drop_index('ix_sessions_user_id', table_name='sessions')
    op.drop_index('ix_sessions_expires_at', table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
